### PR TITLE
refactor: define typescript type for SetRegularKey transaction

### PR DESCRIPTION
**Pull request by mukulljangid**
## High Level Overview of Change
Defines typescript types for SetRegularKey transaction.

### Context of Change
`SetRegularKey` is an extension of CommonFields, and is exported in a type union with all other transaction types defined as Transaction.

We also will provide an optional `verifySetRegularKey` function for runtime form checking of `SetRegularKey` transactions, should the users want to verify transaction form at runtime.

### Type of Change

- [X] Refactor (non-breaking change that only restructures code)

## Test Plan
Adds tests for `verifySetRegularKey`, which provides runtime form verification for `SetRegularKey` transactions

### CODE REVIEW

**Review by mvadari — COMMENTED** [review]
Re-rebase on 2.0 - I can't review this until then

**Review by natenichols — APPROVED** [review]
LGTM 👍

**Comment by mvadari** [comment]
I recommend rebasing instead of merging with 2.0

**Review by mvadari — APPROVED** [review]
looks good, I recommend rebasing instead of merging so the commits aren't as weird

**Review by JST5000 — APPROVED** [review]

**Pull request merged**
