### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by wltsmrz** [comment]
It doesn't look like they've fixed the spread operator bug, but LGTM https://github.com/eslint/eslint/releases/tag/v0.24.0

**Comment by wltsmrz** [comment]
Looks like eslint didn't run?

**Comment by wltsmrz** [comment]
Oh, guess there's nothing to run against, heh

**Comment by sublimator** [comment]
If we're mad keen we could ssh in I guess and run `npm run-script lint` :) ?  May as well just run it locally

**Comment by wltsmrz** [comment]
Ye

**Comment by wltsmrz** [comment]
https://github.com/facebook/jstransform/issues/52  guess this bug belongs to esprima-fb?

**Pull request merged**
