### PR TITLE
Adds Github Actions Testing

### PR DESCRIPTION
**Pull request by natenichols**
## High Level Overview of Change
Runs CI w/ GitHub Actions

### Context of Change
Runs unit tests, linting, and build scripts with Node v12, v13, v14, and `.nvmrc`

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by mvadari** [comment]
Do we still need the build_with_nvm test?

**Review by mvadari — APPROVED** [review]

**Comment by natenichols** [comment]
Nope, we dont need the `.nvmrc` test, then.

**Comment by mvadari** [comment]
Maybe we want to leave it in just in case for the future, though.

**Comment by natenichols** [comment]
I dont have a strong preference either way. I'm okay without it for now

**Review by intelliot — APPROVED** [review]
We may also want to test against 16.x (Current)

https://nodejs.org/en/about/releases/

**Comment by natenichols** [comment]
Sorry about the force push, had to sort our some git issues 😄

**Pull request merged**
