### PR TITLE
[FIX] Amount: to_text_full fix

### PR DESCRIPTION
**Pull request by darkdarkdragon**
turn off group separator in to_text_full

### CODE REVIEW

**Comment by clark800** [comment]
Is this a bug? It looks like a behavioral change and I'm not sure who is using this function.

**Comment by darkdarkdragon** [comment]
I've found this used here
https://github.com/ripple/ripple-client/blob/develop/src/js/tabs/trade.controller.js#L864
this, obviously, throws exception in from_json because to_text_full returns value with separators.

And, looking into to_text_full it has inconsistent behavior - for XRP values it returns number with separators, but for others - without.
So I concluded that this is a bug

**Comment by clark800** [comment]
I agree, I think we should merge this. @darkdarkdragon There are 4 unit tests failing; would you like me to close this pull request and fix them in a new pull request?

**Comment by darkdarkdragon** [comment]
@clark800 Yes, I'll make new pull request

**Pull request closed without merging**
