### PR TITLE
Remove legacy tej* handling from submit error checking

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by lumberj** [comment]
LGTM. Not sure what's wrong with that eslint error

**Comment by lumberj** [comment]
@clark800 did you ever figure out the issue with eslint?

**Comment by clark800** [comment]
I think the best solution is to add `// eslint-disable-line strict` to the `'use strict';` line

**Comment by clark800** [comment]
Replaced with https://github.com/ripple/ripple-lib/pull/714

**Pull request closed without merging**
