### PR TITLE
Not worked code "api.request" at docs. Docs should be updated. #918

### PR DESCRIPTION
**Pull request by spirinvladimir**
My editor trim some trailing space.

### CODE REVIEW

**Comment by intelliot** [comment]
`api.request` is new and requires version 1.0.0-beta.0 (2018-05-10) or later.

**Comment by spirinvladimir** [comment]
I've done initial setup of ripple-lib and tried to subscribe to transactions for my account. Code "api.request" not worked becouse "request" is not a function.

**Comment by intelliot** [comment]
To use api.request, you'll need to use a beta release of ripple-lib at this time. For example, you can specify ripple-lib "1.0.0-beta.3" in your package.json.

**Comment by spirinvladimir** [comment]
@intelliot  thanks. I've start from getstarted example "my_ripple_experiment" and unfortunatly it has version of ripple-lib '*' and it load for me 0.22.0 from npm.

**Pull request closed without merging**
