### PR TITLE
Revert "Set User-Agent Header with ripple-lib/{version}"

### PR DESCRIPTION
**Pull request by boxbag**
Reverts ripple/ripple-lib#286

### CODE REVIEW

**Comment by clark800** [comment]
For future reference and for the open source community, can you add a note about why you are reverting this?

**Comment by boxbag** [comment]
Browser Websocket API is different. This throws an error in the browser when run.

**Comment by clark800** [comment]
So there is currently no way to make it work in the browser? Is this the correct reference for the browser websocket API? https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by boxbag** [comment]
Not to my current knowledge

**Pull request merged**
