### PR TITLE
Don't set paths for XRP to XRP payment

### PR DESCRIPTION
**Pull request by clark800**

### CODE REVIEW

**Comment by clark800** [comment]
Is it possible that someone would want to specify paths for an XRP to XRP payment in order to grab an arbitrage opportunity?

**Comment by lumberj** [comment]
It's an error to set paths for XRP->XRP

**Comment by clark800** [comment]
@lumberj Is that in the documentation?

**Comment by lumberj** [comment]
Documentation actually says, specifying empty paths is an error

**Comment by sublimator** [comment]
LGTM

**Pull request merged**
