### PR TITLE
fix attachTransactionDate in getTransaction

### PR DESCRIPTION
**Pull request by darkdarkdragon**

### CODE REVIEW

**Comment by clark800** [comment]
Mutating function parameters is bad practice. Generally I think mutation is best avoided whenever possible, but mutation of function-local variables is tolerable sometimes for performance.

> There's no test for this?

Apparently not. There's still a lot of code without test coverage. I only wrote minimal tests for the common use cases because testing every path would have slowed down development a lot and the goal is to get something usable out the door quickly. Ivan is working on increasing test coverage now.

**Comment by clark800** [comment]
LGTM

**Comment by sublimator** [comment]
> Mutating function parameters is bad practice. 

I knew you'd say something like that :)

**Comment by clark800** [comment]
There was a good article about mutation on Hacker News today:
https://underthehood.myob.com/functional-programming-in-a-dysfunctional-world/

**Comment by sublimator** [comment]
Oh, I'm sold on immutability and defensive copies etc, but used judiciously.  But I guess you only get the "functional" code reasonability effects if it's a "practice".

Have you played with any of the shared data structures I've seen floating about the traps? Facebook had some lib iirc. I wonder what the impetus was behind these libs?

**Comment by clark800** [comment]
Are you talking about ImmutableJS? https://facebook.github.io/immutable-js/

I was considering whether it's worth using it to enforce immutability more. It would be interesting if eslint had a rule that required all data structures to be created with ImmutableJS :)

**Comment by sublimator** [comment]
Yeah, that's the one

**Comment by sublimator** [comment]
> all data structures to be created with ImmutableJS

Have you seen any codebases out there on your travels that use it pervasively?

**Comment by clark800** [comment]
No, I haven't really been looking though.

**Pull request merged**
