### PR TITLE
Error occurs in Safari

### PR DESCRIPTION
**Pull request by MissMonacoin**
Safari 11 doesn't output object.constructor.name and constructor.toString returns class.

### CODE REVIEW

**Comment by MissMonacoin** [comment]
Is this hack necessary though IE doesn't support ES6?

**Comment by intelliot** [comment]
@MissMonacoin I don't understand what's going on here. What's the error and how do you reproduce it?

**Comment by MissMonacoin** [comment]
Reproduction code: https://github.com/MissMonacoin/ripple_error_reproduction

**Comment by FKSRipple** [comment]
@MissMonacoin thanks for the contribution! Sorry we're just getting to this, since this was a bit old I went ahead and resolved conflicts and then cleaned the code up a bit. Let me know if it looks okay to you

/cc @intelliot for review

**Comment by intelliot** [comment]
Released in 1.4.0

**Pull request merged**
