### PR TITLE
[TASK] Disable parsing native amounts in foating point format

### PR DESCRIPTION
**Pull request by clark800**

### CODE REVIEW

**Comment by geertweening** [comment]
LGTM

**Comment by geertweening** [comment]
please rebase

**Comment by clark800** [comment]
Made small change to orderbook-test.js to fix a test case and rebased. Bo reviewed the change to orderbook-test.js.

**Comment by boxbag** [comment]
LGTM

**Comment by sublimator** [comment]
An opt in would have been nice, so people can do gradual fixes of their code base (eg. rippled test suite)  but other wise stay up to date.  There's always monkey patches, or just biting the bullet and fixing it all up I guess :)

**Comment by sublimator** [comment]
Err, opt out I meant

**Comment by clark800** [comment]
Using drops instead of XRP is a fairly simple change and supposedly it was only used in the test cases for ripple-lib and rippled. Fixing it shouldn't be much harder than setting a flag, either would require changes to the code, so I think it's better to not increase the complexity.

**Comment by sublimator** [comment]
Yeah, not a big deal.

**Pull request merged**
