### PR TITLE
Use ripple-keypairs and ripple-address-codec

### PR DESCRIPTION
**Pull request by sublimator**
Use elliptic for signing

### CODE REVIEW

**Comment by sublimator** [comment]
```
src/core/base.js
  43:5  error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow
  60:5  error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow
  95:5  error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow

src/core/seed.js
  64:7  error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow

src/core/transaction.js
  404:7   error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow
  819:11  error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow
```

I'm not sure what to do about the above, other than disabling no-catch-shadow. I tried just using some obviously unique name, that couldn't possibly be in an upper scope (can't see `e` anywhere either ... ) but it wasn't of much use.

**Comment by sublimator** [comment]
I was having a bit of grief with circle, with failing tests due to old versions of dependencies in the cache. I hit `rebuild with cleared cache` on the circle ui, and now have tests passing, but with eslint now failing (as I have locally, with the v1.1.0 of eslint and the no-catch-shadow)

**Comment by sublimator** [comment]
https://github.com/eslint/eslint/issues/3322

**Comment by sublimator** [comment]
https://github.com/eslint/eslint/pull/3360

**Comment by wltsmrz** [comment]
LGTM

**Comment by clark800** [comment]
LGTM

**Pull request merged**
