### PR TITLE
Added issuer to payment example in guide

### PR DESCRIPTION
**Pull request by lukeburns**
I added issuer information to the payment example. Without it, you get an unhelpful serializing error. 

Solution due to https://github.com/ripple/ripple-lib/issues/28

### CODE REVIEW

**Comment by sublimator** [comment]
I think the from_human parser was changed at one point to require a space between the amount value and the currency. Maybe it just needs to be changed from `1XRP` to `1 XRP`.

**Comment by lukeburns** [comment]
I was wrong. The example works fine (and `from_human` parses both the same). If you're using any other currency, you need to use `set_issuer`, otherwise you get the serializing error.

**Comment by sublimator** [comment]
That makes sense, any serialized amounts, must have issuer specified, even if it's just some neutral issuer ( e.g. the issuer in Balance fields in a RippleState (trustline))

**Comment by lukeburns** [comment]
I think the guide could use some work, so people can play with the examples without immediately getting caught up in errors. Not sure this is the best solution, but it would have saved me and the people in issue #28 a couple hours.

**Comment by sublimator** [comment]
Noted :)

**Comment by clark800** [comment]
LGTM

**Pull request merged**
