### PR TITLE
fix: add amount to FormattedPaymentChannel type

### PR DESCRIPTION
**Pull request by kincaidoneil**
The `amount` field is returned from `getPaymentChannel(<channelId>)` and is [documented](https://github.com/ripple/ripple-lib/blob/develop/docs/index.md#getpaymentchannel), but wasn't included in the type for `FormattedPaymentChannel`.

### CODE REVIEW

**Comment by kincaidoneil** [comment]
Oh, my bad! Fixed.

**Comment by kincaidoneil** [comment]
@intelliot Should I add `package-lock.json` to the .gitignore so it doesn't get accidentally committed in the future?

**Comment by intelliot** [comment]
I think that’s a good idea! 

In the future, if we decide to maintain a package-lock file, we can remove it from gitignore at the same time we commit the new file.

**Comment by kincaidoneil** [comment]
@intelliot Updated!

**Comment by intelliot** [comment]
Perfect - thank you!

**Pull request merged**
