### PR TITLE
[FIX] Amount: to_text_full fix

### PR DESCRIPTION
**Pull request by darkdarkdragon**
turn off group separator in to_text_full

### CODE REVIEW

**Comment by clark800** [comment]
@darkdarkdragon Looks like it's failing the eslint tests. Want me to take this over? Up to you.

**Comment by darkdarkdragon** [comment]
@clark800 I'll fix this

**Comment by darkdarkdragon** [comment]
@clark800 fixed

**Comment by clark800** [comment]
@darkdarkdragon Thanks! LGTM

**Pull request merged**
