### PR TITLE
[TASK] Add eslint enforcement to travis.yml

### PR DESCRIPTION
**Pull request by clark800**
This will require committers to fix all eslint errors in any file that they modify in the pull request.

### CODE REVIEW

**Comment by geertweening** [comment]
How does this decrease coverage? Probably because the Gulpfile is a .js file and we run coverage vs all the test files? Any how it should not affect test coverage

**Comment by geertweening** [comment]
LGTM

**Comment by wltsmrz** [comment]
Does not look good to me

**Comment by clark800** [comment]
@wltsmrz Can you please provide specific reasons for your comment? Unsupported opinions don't contribute much to a rational discussion.

**Comment by wltsmrz** [comment]
I'd just be repeating myself. See the email & my comments on your pull request to the JS style guide for details

**Comment by clark800** [comment]
@wltsmrz I addressed all of your points item by item. If you disagree with any or all of them, please provide an item by item response.

**Comment by wltsmrz** [comment]
I think it's obvious that I disagree. I'll address your comments where appropriate soon

**Pull request merged**
