### PR TITLE
Add TypeScript linting

### PR DESCRIPTION
**Pull request by FredKSchott**
tslint is a linting tool similar to eslint. I took the project's `.eslintrc` and created a `tslint.json` to match it as closely as possible, using a tslint extension called `tslint-eslint-rules` to bring over all the rules not supported natively by tslint.

TypeScript already catches code issues/errors, so tslint can be simplified to focus only on the specific style we want to enforce.

(the linter was already run in the last PR, so no changes needed in the codebase)

/cc @intelliot

### CODE REVIEW

**Comment by mkreidenweis** [comment]
There's still a `"typecheck": "flow check",` script in `package.json`. I assume we don't need that any more since #816, do we?

And there are references to `flow` in `.gitignore` and `scripts/ci.sh`. (CircleCI hasn't actually been running for some at all it seems. Not sure why.)

**Comment by FredKSchott** [comment]
@mkreidenweis great catches! thanks for taking a look 

Fixed everything you mentioned, but ci.sh still has some references to babel that involves a lot of custom options that I can't easily understand/fix. If anyone wants to take a stab feel free, but otherwise lets tackle in a separate PR (also, *is* circle even running anymore? I haven't seen it in a while now)

**Comment by intelliot** [comment]
CircleCI is not used anymore due to security concerns. Any suggestions for an alternative? Jenkins is the most likely candidate.

**Comment by intelliot** [comment]
> Fixed everything you mentioned

Where was it fixed? (Maybe there's a commit that wasn't pushed)

**Comment by intelliot** [comment]
Needs to be rebased due to merging #826 for test coverage

**Comment by FredKSchott** [comment]
doh, looks like my original push failed. Rebased and repushed, ready for another look

@intelliot what security concerns did you see? For Open Source/Github projects I've only ever used Travis & Circle. Loved Travis, but it may suffer from the same security issues as Circle

**Comment by intelliot** [comment]
I'm not sure - I'll check with our team to find out, and we can tackle CI in a future PR.

**Comment by intelliot** [comment]
Thanks!

**Pull request merged**
