### PR TITLE
[FIX] on connect return error if server doesn't have validated ledgers

### PR DESCRIPTION
**Pull request by darkdarkdragon**

### CODE REVIEW

**Comment by clark800** [comment]
LGTM

**Comment by lumberj** [comment]
Isn't this a bug in rippled?

**Comment by lumberj** [comment]
I don't think we're ever testing with servers that have no ledgers

**Comment by darkdarkdragon** [comment]
this happens when server just started and not synced yet. also, when you stop synced server and start it again for some time it is not synced too

**Comment by lumberj** [comment]
> also, when you stop synced server and start it again for some time it is not synced too

Ok makes sense

**Pull request merged**
