### PR TITLE
[FIX] fix AutobridgeCalculator (RT-3445)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
pass issuers to AutobridgeCalculator so
it can create offers with right issuers

### CODE REVIEW

**Comment by clark800** [comment]
Lint checks are failing - we switched to babel, so we have a rule that "var" has to be replaced with "const" or "let". Would you mind making the replacements?

**Comment by darkdarkdragon** [comment]
ok, will do it

**Comment by darkdarkdragon** [comment]
@clark800 done

**Comment by clark800** [comment]
LGTM

**Pull request merged**
