### PR TITLE
Revert "Set default maxLedgerVersion to last closed ledger when reque…

### PR DESCRIPTION
**Pull request by lumberj**
…sting account_tx"

This reverts commit 90b53002aa1e90bf7920f273806dc12ffbcd2107.

account_tx operates against validated ledgers only

### CODE REVIEW

**Comment by clark800** [comment]
Can you add a comment so we don't forget and change it back again?

**Comment by lumberj** [comment]
Added comments, in code (and commit message)

**Comment by clark800** [comment]
"valid" is ambiguous, should say "validated"

**Comment by clark800** [comment]
Also, for "min", it's the most recent validated ledger that is available.

**Comment by clark800** [comment]
Actually, I guess "available" applies for both

**Comment by lumberj** [comment]
@clark800 Updated

**Comment by clark800** [comment]
LGTM

Related: https://ripplelabs.atlassian.net/browse/DEV-153

**Pull request merged**
