### PR TITLE
Refactor API deprecation, fix request constructors with positional args

### PR DESCRIPTION
**Pull request by wltsmrz**

### CODE REVIEW

**Comment by wltsmrz** [comment]
buomp

**Comment by clark800** [comment]
Looks like eslint didn't run. I'm not sure what happened, do you know?

**Comment by wltsmrz** [comment]
Nope

**Comment by clark800** [comment]
Hmmm, I wonder if it's because you are using branches in the same repo? Maybe FETCH_HEAD doesn't get set in that case? Try running through the commands in the CircleCI log to see if you can reproduce.

**Comment by clark800** [comment]
We could also echo the value of FETCH_HEAD in the ci.sh script. Might be useful enough to keep for future debugging needs.

**Pull request closed without merging**
