### PR TITLE
add `create-hash` into npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by darkdarkdragon**
without that npm doesn't install `create-hash` in modules that depends on it

### CODE REVIEW

**Comment by clark800** [comment]
This can't be the right solution: ripple-lib doesn't use create-hash. What's going on here?

**Comment by darkdarkdragon** [comment]
`ripple-binary-codec` and `ripple-hashes` depends on `create-hash`
`create-hash` doesn't get installed because it is not listed as dependency in`npm-shrinkwrap.json` for corresponding modules.
so, I must put it under `ripple-hashes` and `ripple-binary-codec` - and it will be installed into the both location, or put it as direct dependency to `ripple-lib` and it will be installed only once

**Comment by clark800** [comment]
It should be added to the packages that use it

**Comment by darkdarkdragon** [comment]
ok

**Comment by clark800** [comment]
Those packages don't use shrinkwrap though, so I'm confused why it's not working.

**Comment by darkdarkdragon** [comment]
@clark800 can, you, please, restart CircleCI build without cache?

**Comment by clark800** [comment]
Sure, running now

**Comment by darkdarkdragon** [comment]
thanks

**Pull request closed without merging**
