### PR TITLE
docs(react-native): add instructions on how to use ripple-lib with React Native

### PR DESCRIPTION
**Pull request by elmurci**
Adding instructions to README on how to use ripple-lib with React Native.

### CODE REVIEW

**Comment by mikecheckyaself** [comment]
I made a [video ](https://youtu.be/rE6eZxtk8Jc )about integrating Ripple-lib with react-native about a year ago. Haven't tried to do it on more recent versions of react-native but, it required a few more dependencies back then. When I get a chance later I will make an attempt with your instructions and provide my feedback.

**Comment by mrosendin** [comment]
I'm coming from an expo project. I did `expo eject` and it was a pretty bumpy road, but I was able to build the RN app. 

Other methods seem to work but calling the RippleAPI method `generateXAddress` gave me this error =>
`[UnexpectedError: undefined is not an object (evaluating 'Transform.call')]`

🤷‍♂️

**Comment by elmurci** [comment]
> I'm coming from an expo project. I did `expo eject` and it was a pretty bumpy road, but I was able to build the RN app.
> 
> Other methods seem to work but calling the RippleAPI method `generateXAddress` gave me this error =>
> `[UnexpectedError: undefined is not an object (evaluating 'Transform.call')]`
> 
> 🤷‍♂️

Hey @mrosendin :-)
I am not very familiar with Expo, but I have created a new app and imported `ripple-lib` and all seemed to work fine.

```
import React from 'react';
...
import {RippleAPI} from 'ripple-lib';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { address: 'not_set' };
  }
  componentDidMount() {
    const api = new RippleAPI({
      server: 'wss://s.altnet.rippletest.net:51233'
    });
    const xAddress = api.generateXAddress();
    this.setState({
      address: xAddress
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>Address: {this.state.address.xAddress}</Text>
      </View>
    );
  }
}

...
```

Could you share your code maybe?

**Comment by mrosendin** [comment]
Got it working after I had run `./node_modules/.bin/rn-nodeify --hack --install` one last time, @elmurci!

I also get this error message when the app is building. 

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-randombytes (to unlink run: "react-native unlink react-native-randombytes")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

It seems the step for explicit linking is not required for >= RN 0.60.

**Comment by intelliot** [comment]
@mrosendin can you confirm whether these instructions work for you? If not, can you comment with instructions that would work?

Thanks!

#1387

**Comment by mrosendin** [comment]
Hey @intelliot, they did work for me (RN v0.63.4)

**Comment by intelliot** [comment]
Fixed by #1387

**Pull request closed without merging**
